### ISSUE TITLE
Custom extraction does not work when the value is an empty string

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/microdata#126]
### 👓 What did you see?

We're writing a custom field extraction where the value can be an empty string. The value is stored in an `input` field.
We're getting an error when the field is empty, as our custom extractor returns an empty string and `micro data`fallback to the default extractor (which does not handle `input` fields).

### ✅ What did you expect to see?

As per the documentation:

> This function may return undefined. In that case, the default lookup mechanisms will be used.

I was expecting the empty string to be taken into account, not the default lookup mechanism.

I'll do a PR ASAP to fix that ;)

**Comment by aslakhellesoy** [comment]
Fixed in #127.
