### ISSUE TITLE
Does not find Product

### ISSUE THREAD

**Issue by motiejunas** [cucumber/microdata#7]
Awesome lib. However, can't extract Product microdata on some stores.

Example URL:
https://istore.lt/apple-airpods-pro-bevieles-ausines.html

The schema is valid according Rich Results Test:
https://search.google.com/test/rich-results?id=wOK-K-YfUK13SSVwhnMtRg

Code fragment:
```
const product = microdata<Product>('http://schema.org/Product', document as any);

console.log(product);
```

Gives ```null```.

Another example:
https://search.google.com/test/rich-results?id=hIWuJh2WU7IlhWC2Jy85Hw

**Comment by motiejunas** [comment]
Oh gosh, that's my mistake. Just went thought the code and see that this lib does handle (look for) "application/ld+json" at all.

**Comment by gardner** [comment]
I think there may be a confusing typo in the above response. I wasn't able to find any jsonld processing in this library. It's still rad. Thanks for publishing it.
